### ISSUE TITLE
Create data paper mockups

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/project-papers#13]
We created the data paper wireframes already. We want to expand on that wireframe and create a hifi mockup that represents what the data paper will actually look like in the UI, focusing on fonts, colors, alignment, and other "pixel perfect" design.

This mockup can be shown the SASAP working groups for feedback since it will look more like a user interface.

**Comment by mbjones** [comment]
Need to update mockups to reflect recent changes in EML 2.2 work, and check the graphical files into git.
