### ISSUE TITLE
Create mockups for static visualizations in the data paper layout

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/project-papers#15]
We created the data paper wireframes already. We want to expand on that wireframe and create a hifi mockup that represents what the data paper will actually look like in the UI, focusing on fonts, colors, alignment, and other "pixel perfect" design.

This mockup can be shown the SASAP working groups for feedback since it will look more like a user interface.

**Comment by mbjones** [comment]
Initial mockups were completed.
