### ISSUE TITLE
Determine what changes are needed to the EML spec for the data paper layout

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/project-papers#21]
This Github issue was taken from a post-it note during our in-person Feb 8 meeting. The post-it said, "See if you can build all text from present EML." 

If the post-it author could add a bit more clarification on what that meant exactly, or just confirm that `Determine what changes are needed to the EML spec for the data paper layout` is an accurate title, then that would be helpful.

**Comment by mbjones** [comment]
I think what we want to do here is tom compare the needs for project pages to what is already in EML.  We would then consider adding any missing fields to EML as needed. 

I just added issue #41 and #42 describing example documents that would help us to determine if the project schema suffices.
