### ISSUE TITLE
Evaluate/modify EML data paper proposal

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/project-papers#22]
We need to look back at the EML data paper proposal and make sure it meets the needs of the new data portal paper design. If not, we need to modify the proposal to support that new feature.

**Comment by mbjones** [comment]
The EML data paper proposal has been implemented in the nascent EML 2.2 release, and is awaiting review and release.  See https://github.com/NCEAS/eml/issues/269 for an overview.
