### ISSUE TITLE
Develop proposal to implement in-line images in EML schema

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/project-papers#23]
Both project pages and data papers need the ability to reference inline images and tables so they can be displayed at the appropriate locations in data paper or project page.  Modify EML to include such references.  The likely best way to do this is to 1) include all images and objects to be inlined as entities in the EML document, and 2) create a mechanism for referencing those locally.

**Comment by mbjones** [comment]
Proposed to use Markdown in text blocks for image layouts. See https://github.com/NCEAS/eml/issues/275.
