### ISSUE TITLE
Complete and prioritize feature list for project pages

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/project-papers#32]
We need to use our wireframes and recent discussions to complete a comprehensive list of features to implement for the project pages. Then we need to create Github issues for each tasks associated with those features and prioritize them into milestones.

**Comment by jeanetteclark** [comment]
Feature list for project pages here: https://docs.google.com/document/d/1_s46bIdMT8cGRFPpunHr8JHic4AAI3I-TCXiYS1cKg0/edit

**Comment by emilyodean** [comment]
Associated ticket - https://github.com/NCEAS/metacatui/issues/445

**Comment by emilyodean** [comment]
Desired features are essentially captured in the [collection schema](https://github.com/NCEAS/project-papers/blob/master/project-schema/metacatui-collection.json) and [project schema](https://github.com/NCEAS/project-papers/blob/master/project-schema/metacatui-project.xsd) documents and visualized in the [wireframe](https://projects.invisionapp.com/freehand/document/2ZaMAx4vb). 

Will work on creating a plant UML diagram.
