### ISSUE TITLE
Determine schema serialization for Collections/Projects

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/project-papers#4]
RDF XML?

**Comment by mbjones** [comment]
JSON-LD?

**Comment by emilyodean** [comment]
Project and collection serialization is captured in [this folder](https://github.com/NCEAS/project-papers/tree/master/project-schema).

`metacatui-project.xsd` contains project schema and `metacatui-project.xml` is a working example project document which validates against the schema.

`metacatui-collection.json` contains the collection/filter schema and `exmplecollection.json` is a working example of a collection. `metacatui-collection-definitions.json` contains definitions for all json attributes.
