### ISSUE TITLE
example data paper from SASAP

### ISSUE THREAD

**Issue by mbjones** [NCEAS/project-papers#44]
Create an example data paper in EML 2.2 format from one of our highly curated SASAP data products.  @jeanetteclark and @smfreund to review possibilities and propose a candidate.

**Comment by jeanetteclark** [comment]
I think this is a good candidate: https://knb.ecoinformatics.org/#view/urn:uuid:0d5b43f0-e43a-42ab-80af-cb68b1c73fa9

It needs a little more work though

- [ ] Describe the processing steps in the Rmd in detail in the methods section

- [ ] Create figures in Rmd. One should be change in % of native language speakers between 1990 and 2015, another should somehow show the diversity of languages in 2015

- [ ] Add exported versions of figures to dataset as browse graphics

**Comment by jeanetteclark** [comment]
Sounds like we need a dataset that has multiple tables in it - this is the next best candidate: https://knb.ecoinformatics.org/#view/urn:uuid:8746daec-c8a9-40c9-8d15-9f0d68269ebd
