### ISSUE TITLE
relabel all project-papers issues for easy filtering

### ISSUE THREAD

**Issue by mbjones** [NCEAS/project-papers#60]
The Project-papers project involves tasks that span multiple repositories and that can all be displayed in the [project-papers waffle board](https://waffle.io/NCEAS/project-papers).  The problem arises that MetacatUI and other repos have many unrelated tickets as well.  We can fix this issue through the consistent use of labels for all tickets in all repositories.  We need to assign a 
`Projects-Papers` label to all tickets in all repositories that are part of this project.  That will allow waffle to filter to the subset of relevant tickets for this project.

While doing this, we should also assign the proper sub-project labels that we decided to use, including the Category labels that start with 'Cat' and subset the project tasks into categories of work.

The tickets for this project are now best seen through this link:
https://waffle.io/NCEAS/project-papers?label=Projects-Papers

**Comment by mbjones** [comment]
I started the `Projects-Papers` label and assigned it to the main issues for the current repository.  @jkibele Could you please review the tickets in the MetacatUI repository and ensure that any tickets there are appropriately labeled? You can review any questions with @laurenwalker as needed.  Thanks.

**Comment by jkibele** [comment]
I went through all of them that weren't labelled as `bug` (figured those wouldn't be part of `Project-Papers`). I added the label to a few. I'm not super confident that I did it all perfectly, but I can give it another pass once I'm up to speed on what's going on.

**Comment by mbjones** [comment]
Thanks.
