### ISSUE TITLE
Restrict project view search to project collection items

### ISSUE THREAD

**Issue by jkibele** [NCEAS/project-papers#61]
I'm breaking out this issue from [a more general issue](https://github.com/NCEAS/project-papers/issues/35). I suspect I'm going to need to have some back and forth about this, and I can use it to track what I'm doing.

**Comment by laurenwalker** [comment]
I vote that we put these detailed coding tasks in the `metacatui` github issues

**Comment by jkibele** [comment]
Okay. ...I wondered about that. I just made the same thing over there. I'll close this one.

**Comment by mbjones** [comment]
That works, but please be sure to label the MetcatUI issues properly with the 'Projects-Papers' label and appropriate subproject labels.
