### ISSUE TITLE
Acknowledgements misspelled in project schema

### ISSUE THREAD

**Issue by jkibele** [NCEAS/project-papers#66]
This is a pretty minor thing, but I noticed that "acknowledgements" is misspelled [in the project schema](https://github.com/NCEAS/project-papers/blob/cde75931cdcf8f1c925ab1f977a083c6f6e4b860/schemas/metacatui-project.xsd#L66). It's missing an 'e'. This is also propagated into the example SASAP project, so I had to misspell it in a template related to NCEAS/metacatui#825.  

I could edit it in this repo, but I don't know how to push that through to the example document so I figured I'd flag @laurenwalker here.

**Comment by laurenwalker** [comment]
They are both correct spellings -- see https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Spelling

`acknowledgment` seems to be the American English way while `acknowledgement` is the British English way

**Comment by jkibele** [comment]
Sorry about that. I reckon I've spent too much time down in Aotearoa. Yank spellings look a bit sus now. Chur!
